# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, calculator):
        calculator.setObjectName("calculator")
        calculator.resize(479, 573)
        font = QtGui.QFont()
        font.setPointSize(10)
        calculator.setFont(font)
        self.label = QtWidgets.QLabel(calculator)
        self.label.setGeometry(QtCore.QRect(20, 10, 411, 81))
        self.label.setMaximumSize(QtCore.QSize(167772, 1677))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.C = QtWidgets.QPushButton(calculator)
        self.C.setGeometry(QtCore.QRect(350, 100, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.C.setFont(font)
        self.C.setObjectName("C")
        self.pushButton_10 = QtWidgets.QPushButton(calculator)
        self.pushButton_10.setGeometry(QtCore.QRect(240, 100, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.power = QtWidgets.QPushButton(calculator)
        self.power.setGeometry(QtCore.QRect(20, 100, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.power.setFont(font)
        self.power.setObjectName("power")
        self.squareRoot = QtWidgets.QPushButton(calculator)
        self.squareRoot.setGeometry(QtCore.QRect(130, 100, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.squareRoot.setFont(font)
        self.squareRoot.setObjectName("squareRoot")
        self.number_5 = QtWidgets.QPushButton(calculator)
        self.number_5.setGeometry(QtCore.QRect(130, 280, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number_5.setFont(font)
        self.number_5.setObjectName("number_5")
        self.number_8 = QtWidgets.QPushButton(calculator)
        self.number_8.setGeometry(QtCore.QRect(130, 190, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number_8.setFont(font)
        self.number_8.setObjectName("number_8")
        self.number_3 = QtWidgets.QPushButton(calculator)
        self.number_3.setGeometry(QtCore.QRect(240, 370, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number_3.setFont(font)
        self.number_3.setObjectName("number_3")
        self.number_6 = QtWidgets.QPushButton(calculator)
        self.number_6.setGeometry(QtCore.QRect(240, 280, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number_6.setFont(font)
        self.number_6.setObjectName("number_6")
        self.multiplication = QtWidgets.QPushButton(calculator)
        self.multiplication.setGeometry(QtCore.QRect(350, 370, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.multiplication.setFont(font)
        self.multiplication.setObjectName("multiplication")
        self.minus = QtWidgets.QPushButton(calculator)
        self.minus.setGeometry(QtCore.QRect(350, 280, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.minus.setFont(font)
        self.minus.setObjectName("minus")
        self.number_9 = QtWidgets.QPushButton(calculator)
        self.number_9.setGeometry(QtCore.QRect(240, 190, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number_9.setFont(font)
        self.number_9.setObjectName("number_9")
        self.sum = QtWidgets.QPushButton(calculator)
        self.sum.setGeometry(QtCore.QRect(350, 190, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.sum.setFont(font)
        self.sum.setObjectName("sum")
        self.number_4 = QtWidgets.QPushButton(calculator)
        self.number_4.setGeometry(QtCore.QRect(20, 280, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number_4.setFont(font)
        self.number_4.setObjectName("number_4")
        self.number_7 = QtWidgets.QPushButton(calculator)
        self.number_7.setGeometry(QtCore.QRect(20, 190, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number_7.setFont(font)
        self.number_7.setObjectName("number_7")
        self.number_2 = QtWidgets.QPushButton(calculator)
        self.number_2.setGeometry(QtCore.QRect(130, 370, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number_2.setFont(font)
        self.number_2.setObjectName("number_2")
        self.number_1 = QtWidgets.QPushButton(calculator)
        self.number_1.setGeometry(QtCore.QRect(20, 370, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number_1.setFont(font)
        self.number_1.setObjectName("pushButton")
        self.decimal = QtWidgets.QPushButton(calculator)
        self.decimal.setGeometry(QtCore.QRect(20, 460, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.decimal.setFont(font)
        self.decimal.setObjectName("decimal")
        self.number_0 = QtWidgets.QPushButton(calculator)
        self.number_0.setGeometry(QtCore.QRect(130, 460, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number_0.setFont(font)
        self.number_0.setObjectName("number_0")
        self.equal = QtWidgets.QPushButton(calculator)
        self.equal.setGeometry(QtCore.QRect(240, 460, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.equal.setFont(font)
        self.equal.setObjectName("equal")
        self.division = QtWidgets.QPushButton(calculator)
        self.division.setGeometry(QtCore.QRect(350, 460, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.division.setFont(font)
        self.division.setObjectName("division")

        self.retranslateUi(calculator)
        QtCore.QMetaObject.connectSlotsByName(calculator)

    def retranslateUi(self, calculator):
        _translate = QtCore.QCoreApplication.translate
        calculator.setWindowTitle(_translate("calculator", "calculator"))
        self.C.setText(_translate("calculator", "C"))
        self.pushButton_10.setText(_translate("calculator", "PushButton"))
        self.power.setText(_translate("calculator", "^"))
        self.squareRoot.setText(_translate("calculator", u"\u221A"))
        self.number_5.setText(_translate("calculator", "5"))
        self.number_8.setText(_translate("calculator", "8"))
        self.number_3.setText(_translate("calculator", "3"))
        self.number_6.setText(_translate("calculator", "6"))
        self.multiplication.setText(_translate("calculator", "X"))
        self.minus.setText(_translate("calculator", "-"))
        self.number_9.setText(_translate("calculator", "9"))
        self.sum.setText(_translate("calculator", "+"))
        self.number_4.setText(_translate("calculator", "4"))
        self.number_7.setText(_translate("calculator", "7"))
        self.number_2.setText(_translate("calculator", "2"))
        self.number_1.setText(_translate("calculator", "1"))
        self.decimal.setText(_translate("calculator", "."))
        self.number_0.setText(_translate("calculator", "0"))
        self.equal.setText(_translate("calculator", "="))
        self.division.setText(_translate("calculator", "÷"))

